# show -g ... to get current
# set -gu ... to unset (back to default)

# default binding is mark window, which I don't use
bind m set -g mouse \; display "mouse #{?mouse,on,off}"
# move current pane to window 0
bind j join-pane -t :0

set -g mouse

set -g status-left ""
set -g status-right ""
# set -g status-right "\"#{=40:pane_title}\""

set -g status-style 'fg=brightblack,bg=white'
set -g status-right-style 'fg=black,bg=white'
set -g window-status-current-style 'fg=black,bg=brightwhite'

# can't remember those vague flags, useless
set -g window-status-format '#I·#W'
set -g window-status-current-format ' #I·#W '

# copy mode
set -g mode-keys vi
# command mode
set -g status-keys emacs

